### ISSUE TITLE
two questions...

### ISSUE THREAD

**Issue by moebiussurfing** [kritzikratzi/ofxNative#3]
hey thanks for this, I am looking for some screen/window manager...

1. do you have any example?

2. do you use any settings save/load? It would be nice to have a JSON to store/recall all the 'window related states' to add easily to ofApp.
There's some useful window serializers here:
https://github.com/bakercp/ofxSerializer/blob/master/src/ofxSerializer.h

**Comment by kritzikratzi** [comment]
hey! 

there are no examples as of yet. 
you need to add the cpp file for your platform to your project, nothing else (e.g. ofNative_lin.cpp). 

then everything is static, so you'd use it like this: 

    string path = ofxNative::getSystemDataFolder() + "/settings.json"; 
    // now use ofxSerializer or whatever to read/write your settings...


or, another example: 

    auto path = ofToDataPath("help.pdf", true); 
    ofxNative::openFile(path); // open help.pdf with default app
    ofxNative::showFile(path); // show help.pdf in explorer/finder/....


hope this helps. 

closing this, because reading/writing settings is not in the scope of this library as far as i'm concerend. 

if you want to contribute examples (or the much needed addon_config.mk) you're more than welcome (please pr).
