### ISSUE TITLE
OSX support fails to compile when building on Ubuntu, for Ubuntu

### ISSUE THREAD

**Issue by DJLevel3** [kritzikratzi/ofxNative#5]
When compiling Oscilloscope (which depends on ofxNative) on Ubuntu, there is a compiler error in the osx portion of ofxNative where it cannot find Cocoa/Cocoa.h or Frameworks/Frameworks.h. I can't figure out how to actually fix it, and it may be Ubuntu specific, but commenting out the entire file worked for me so maybe adding an optional flag to disable one or more platforms would make the process easier for non-OSX users.

**Comment by kritzikratzi** [comment]
thank you, yes! i checked and saw the issue was fixed even before the bug report. the oscilloscope application references an older commit which is why the error still shows up there. but if you do a `git pull origin master` on ofxNative the problem should go away. 

closing this, if the issue does persist or come up again feel free to reopen or make a new one. 

thanks for the bug report either way!
